import { ChevronDown, Clock3, Database, RefreshCw } from 'lucide-react';
import type { SearchResult, Snapshot } from '../domain/schema.js';
import { dateTime, shortDate } from '../lib/view.js';

type Props = { snapshot: Snapshot; result: SearchResult; onRefresh: () => void; busy: boolean; capabilities: boolean };

export function CoveragePanel({ snapshot, result, onRefresh, busy, capabilities }: Props) {
  const searched = snapshot.sourceRuns.filter(run => ['queried','fetched','imported'].includes(run.status));
  const attempted = snapshot.sourceRuns.filter(run => run.status !== 'not_searched');
  const gaps = snapshot.sourceRuns.filter(run => ['blocked','failed','not_searched'].includes(run.status));
  const dates = snapshot.homes.map(h => h.lastObservedAt).sort();
  const merged = snapshot.sourceRuns.reduce((sum, run) => sum + run.duplicateObservations, 0);
  return <div className="coverage-block"><div className="coverage-strip"><div className="coverage-primary"><Database size={15}/><strong>{snapshot.homes.length} distinct home{snapshot.homes.length === 1 ? '' : 's'}</strong><span className="coverage-divider"/><span>{result.counts.matches} meet requirements</span><span>{result.counts.needsVerification} need verification</span><span>{result.counts.nearMatches} near matches</span></div><div className="coverage-secondary"><span className="mono">{searched.length} sources searched · checked {dates.length ? `${shortDate(dates[0])}–${shortDate(dates[dates.length - 1])}` : dateTime(snapshot.createdAt)}</span><button className="refresh-button" onClick={onRefresh} disabled={busy || !capabilities} title={capabilities ? 'Search supported sources again' : 'Live discovery unavailable'}><RefreshCw size={13} className={busy ? 'spinning' : ''}/> {busy ? 'Searching' : 'Refresh'}</button><details className="coverage-disclosure"><summary>Coverage <ChevronDown size={13}/></summary><div className="coverage-pop"><h3>Where this search looked</h3><p>{attempted.length} sources attempted · {searched.length} searched · {snapshot.homes.length} distinct home records · {merged} duplicate observations reconciled.</p><p className="muted">These counts describe recorded research, not a percentage of the housing market.</p><div className="coverage-runs">{snapshot.sourceRuns.map(run => { const source = snapshot.sources.find(s => s.id === run.sourceId); return <div key={run.sourceId} className="coverage-run"><strong>{source?.name ?? run.sourceId}</strong><span className="mono">{run.status.replaceAll('_',' ')} · {dateTime(run.completedAt)}</span><p>{run.queryDescription || run.method}{run.bounds ? ` · ${run.bounds}` : ''}{run.error ? ` · ${run.error}` : ''}{source?.limitation ? ` · ${source.limitation}` : ''}</p><small>{run.pagesFetched} pages fetched · {run.observations} observations · {run.importedHomeIds.length} home IDs imported</small></div>; })}</div>{gaps.length > 0 && <p className="coverage-gap">Gaps: {gaps.map(run => snapshot.sources.find(s => s.id === run.sourceId)?.name ?? run.sourceId).join(', ')}.</p>}{snapshot.researchScopes.flatMap(scope => scope.limitReasons).length > 0 && <p>Research limits: {snapshot.researchScopes.flatMap(scope => scope.limitReasons).join(' · ')}</p>}</div></details></div></div></div>;
}
