import { ArrowLeft, ArrowUpRight, Bookmark, GitCompareArrows, MapPin } from 'lucide-react';
import type { Criteria, EvaluatedHome, Fact, Home, Snapshot } from '../domain/schema.js';
import { dateTime, dollars, fitLabel, homeRoute, layout, minute, title, utilities, utilityFor, utilityState, wholeRentLabel } from '../lib/view.js';

type Props = { snapshot: Snapshot; criteria: Criteria; home: Home; result: EvaluatedHome; onBack: () => void; saved: boolean; comparing: boolean; onSave: () => void; onCompare: () => void };

function FactEvidence({ snapshot, fact }: { snapshot: Snapshot; fact: Fact<unknown> }) {
  if (!fact.evidenceIds.length) return <span className="fact-state">{fact.state === 'derived' ? 'Calculated from stated inputs' : fact.state === 'assumed' ? 'Assumption' : 'Not stated in source'}</span>;
  return <details className="fact-evidence"><summary>{fact.state === 'conflicting' ? 'Conflicting evidence' : 'View evidence'}</summary>{fact.evidenceIds.map(id => { const evidence = snapshot.evidence.find(e => e.id === id); const source = snapshot.sources.find(s => s.id === evidence?.sourceId); return evidence && <div key={id} className="evidence-citation"><div className="mono">{source?.name ?? evidence.sourceId} · {dateTime(evidence.observedAt)} · {evidence.scopeKind.replaceAll('_',' ')}</div><p>{evidence.excerpt}</p><a href={evidence.url} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={12}/></a></div>; })}</details>;
}

function Datum({ label, value, detail, children }: { label: string; value: React.ReactNode; detail?: string; children?: React.ReactNode }) {
  return <div className="datum"><dt>{label}</dt><dd><div>{value}</div>{detail && <small>{detail}</small>}{children}</dd></div>;
}

export function HomeDetail({ snapshot, criteria, home, result, onBack, saved, comparing, onSave, onCompare }: Props) {
  const route = homeRoute(snapshot, result);
  return <div className="detail-view" role="region" aria-label={`Details for ${title(home)}`}>
    <div className="detail-top"><button className="back-button" onClick={onBack}><ArrowLeft size={17}/> All homes</button><span className="mono">{fitLabel(result)}</span></div>
    <div className="detail-heading"><div><div className="eyebrow">Home record / {home.scope.replaceAll('_',' ')}</div><h2>{title(home)}</h2><p>{home.propertyType.value ?? 'Type unknown'} · {layout(home)} {home.unitLabel.value && `· ${home.unitLabel.value}`}</p></div><span className="detail-observed mono">Observed {dateTime(home.lastObservedAt)}</span></div>
    <div className="detail-actionbar"><button className={`plain-button ${saved ? 'active' : ''}`} onClick={onSave}><Bookmark size={15} fill={saved ? 'currentColor' : 'none'}/>{saved ? 'In shortlist' : 'Add to shortlist'}</button><button className={`plain-button ${comparing ? 'active' : ''}`} onClick={onCompare}><GitCompareArrows size={15}/>{comparing ? 'In comparison' : 'Compare'}</button><a className="plain-button primary-button" href={home.primaryUrl} target="_blank" rel="noreferrer">Original listing <ArrowUpRight size={15}/></a></div>
    <div className="detail-hero-facts"><div><span className="eyebrow">Personal base rent</span><strong>{dollars(result.cost.personalBaseRent)}</strong><small>{result.cost.personalBaseRent == null ? 'Basis or offer needs verification' : `Calculated · ${result.cost.allocationLabel}`}</small></div><div><span className="eyebrow">Walking to {criteria.destination.label}</span><strong className="route-color">{route?.status === 'ok' ? minute(route.durationSeconds) : 'Unverified'}</strong><small>{route?.status === 'ok' ? 'Computed foot route' : 'No qualifying route in this snapshot'}</small></div></div>
    <section className="detail-section"><h3>What fits, and what needs checking</h3><div className="constraint-list">{result.constraints.map(c => <div key={c.key} className={`constraint ${c.outcome}`}><span>{c.key.replaceAll('_',' ')}</span><strong>{c.outcome === 'pass' ? 'Confirmed' : c.outcome === 'fail' ? 'Outside limit' : 'Unknown'}</strong><small>{c.actual == null ? 'No confirmed value' : `${c.actual}${c.unit ? ` ${c.unit}` : ''}`}{c.outcome === 'fail' && c.delta != null ? ` · ${Math.abs(c.delta)} ${c.unit ?? ''} beyond limit` : ''}</small></div>)}</div></section>
    <section className="detail-section"><h3>Rent & other costs</h3><dl className="datum-list"><Datum label="Advertised base rent" value={wholeRentLabel(home)} detail={`${home.rent.semantics.replaceAll('_',' ')} · ${home.rent.kind} quote`}><FactEvidence snapshot={snapshot} fact={home.rent.amount}/></Datum><Datum label="Your calculated share" value={dollars(result.cost.personalBaseRent)} detail={result.cost.allocationLabel}/><Datum label="Known monthly housing cost" value={result.cost.knownPersonalRecurring == null ? 'Cannot calculate' : `${dollars(result.cost.knownPersonalRecurring)} + unresolved charges`} detail={result.cost.completeness.replaceAll('_',' ')}/>{home.charges.map(charge => <Datum key={charge.id} label={`${charge.label} · ${charge.cadence.replaceAll('_',' ')}`} value={dollars(charge.amount.value)} detail={`${charge.allocation.replaceAll('_',' ')} · ${charge.required.value == null ? 'requirement not stated' : charge.required.value ? 'required' : 'optional'}`}><FactEvidence snapshot={snapshot} fact={charge.amount}/></Datum>)}<Datum label="Concessions" value={home.concessions.value || 'Not stated'}><FactEvidence snapshot={snapshot} fact={home.concessions}/></Datum></dl>{result.cost.unknownItems.length > 0 && <div className="unresolved-panel"><strong>Costs still unresolved</strong><ul>{result.cost.unknownItems.map(item => <li key={item.key}><b>{item.key.replaceAll('_',' ')}</b> — {item.reason}</li>)}</ul></div>}</section>
    <section className="detail-section"><h3>Utilities in advertised rent</h3><div className="utility-detail-list">{utilities.map(({ key, label }) => { const u = utilityFor(home,key); return <div className="utility-detail" key={key}><strong>{label}</strong><span className={utilityState(u) === 'not stated' ? 'warning' : ''}>{utilityState(u)}</span><small>{u?.terms.value || (u?.inclusion.value === 'separate' ? 'Amount may depend on usage' : u?.inclusion.value === 'included' ? 'Included according to source' : 'No terms stated')}</small>{u && <FactEvidence snapshot={snapshot} fact={u.inclusion}/>}</div>; })}</div></section>
    <section className="detail-section"><h3>Daily life around this home</h3><dl className="datum-list"><Datum label="Walking route" value={route?.status === 'ok' ? `${minute(route.durationSeconds)} · ${route.distanceMeters == null ? 'distance unknown' : `${(route.distanceMeters / 1000).toFixed(2)} km`}` : route ? route.status.replaceAll('_',' ') : 'Not computed'} detail={route ? `${route.provider} · foot profile · ${dateTime(route.computedAt)}` : 'Route needed'} /><Datum label="Destination" value={<><MapPin size={15}/> {criteria.destination.label}</>} detail={`Mapped entrance · ${criteria.destination.coordinate.lat.toFixed(6)}, ${criteria.destination.coordinate.lon.toFixed(6)}. ${criteria.destination.caveat || ''}`} /><Datum label="Nearby transit" value={home.transit.length ? home.transit.map(t => <div key={`${t.originStopId}-${t.routeShortName}`}>Route {t.routeShortName} · {t.originStopName} · {t.headsign} <small>{t.servesDestination ? 'serves destination on verified trip' : 'nearby stop; destination service unverified'} · {Math.round(t.distanceMeters)} m {t.distanceBasis.replaceAll('_',' ')}</small></div>) : 'No transit context in snapshot'} /><Datum label="Nearby errands" value={home.nearby.length ? home.nearby.slice(0,6).map(place => <div key={place.id}>{place.name} · {place.category} <small>{Math.round(place.distanceMeters)} m {place.distanceBasis.replaceAll('_',' ')}{place.walkSeconds == null ? '' : ` · ${minute(place.walkSeconds)} walking`}</small></div>) : 'No nearby places recorded; this does not mean none exist'} /><Datum label="Features & perks" value={home.amenities.length ? home.amenities.map(a => <div key={a.key}>{a.label}: {a.fact.value === true ? 'yes' : a.fact.value === false ? 'no' : a.fact.value ?? 'not stated'} <small>{a.scope} evidence</small></div>) : 'No features recorded'} /><Datum label="Reviews" value={home.reviews.length ? home.reviews.map(r => <div key={r.key}>{r.label}: {String(r.fact.value ?? 'not stated')} <small>{r.scope} scope</small></div>) : 'No sourced reviews recorded'} /></dl></section>
    <section className="detail-section"><h3>Before you investigate or tour</h3><ol className="question-list">{result.questions.length ? result.questions.sort((a,b) => a.priority - b.priority).map(q => <li key={q.key}>{q.text}</li>) : <li>Confirm current availability, charges, and listing terms with the source.</li>}</ol><dl className="datum-list"><Datum label="Availability stated" value={home.availability.value ?? 'Not stated'}><FactEvidence snapshot={snapshot} fact={home.availability}/></Datum><Datum label="Lease terms stated" value={home.leaseTerms.value ?? 'Not stated'}><FactEvidence snapshot={snapshot} fact={home.leaseTerms}/></Datum></dl></section>
  </div>;
}
